$(function(){
  const $sections=$('section[id]'),$links=$('.nav-link[data-section]');
  $('.examples-index span:last-child small').text('Final');
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const id=entry.target.id;$links.removeClass('active').filter('[data-section="'+id+'"]').addClass('active');$(entry.target).find('.reveal').each(function(i){$(this).css('transition-delay',(i*90)+'ms').addClass('in-view')})}}),{threshold:.28});
  $sections.each(function(){observer.observe(this)});
  $('a[href^="#"]').on('click',function(e){const target=$(this).attr('href');if($(target).length){e.preventDefault();$(target)[0].scrollIntoView({behavior:'smooth'})}});
  $(window).on('scroll',function(){const max=document.documentElement.scrollHeight-window.innerHeight;$('.progress span').css('width',Math.min(100,(window.scrollY/max)*100)+'%');if(window.innerWidth>760){const x=(window.innerWidth/2-window.scrollX)*.0006;$('.hero-visual').css('transform','translate3d('+(x*18)+'px,'+(x*7)+'px,0)')}}).trigger('scroll');
  $('.copy-btn').on('click',function(){navigator.clipboard.writeText($(this).data('copy'));$('.copy-feedback').addClass('show');setTimeout(()=>$('.copy-feedback').removeClass('show'),1600)});
  const mdNodes={project:['Project Structure','Dosya yapısı ve yönlendirme','Obsidian/00-root-general-information.md'],stack:['Tech Stack Knowledge','Kullanılan teknolojiler','Obsidian/03-frontend-paketler.md'],architecture:['Architecture Rules','Mimari yapı ve katmanlar','Obsidian/00-root-general-information.md'],style:['Code Style & Best Practices','Tutarlı kod üretimi','Obsidian/05-uygulama-workflow.md'],previous:['Previous Projects','Benzer kod yapısı','Obsidian/04-active-context.md'],output:['Output Guidelines','Net çıktı formatı','Obsidian/05-uygulama-workflow.md'],task:['Task Instructions','Açık ve detaylı yönerge','Obsidian/05-planlama-workflow.md'],files:['Relevant Files','Hangi dosyalarla çalışılacağı','Obsidian/00-root-general-information.md'],solid:['SOLID Principles','Temiz ve sürdürülebilir kod','Obsidian/00-root-general-information.md'],avoid:['Avoid Hallucination','Gereksiz üretimi önleme','Obsidian/00-root-general-information.md'],token:['Token Efficiency','Daha verimli çalışma','Obsidian/00-root-general-information.md']};
  $('.graph-lines [data-link="project"]').attr('d','M500 250 C500 205 500 150 500 105');
  $('.graph-lines [data-link="architecture"]').attr('d','M500 250 C405 225 285 220 112 200');
  $('.graph-lines [data-link="style"]').attr('d','M500 250 C390 285 275 315 112 328');
  $('.graph-lines [data-link="stack"]').attr('d','M500 250 C425 205 300 170 250 100');
  $('.graph-lines [data-link="task"]').attr('d','M500 250 C570 210 700 170 794 100');
  $('.graph-lines [data-link="files"]').attr('d','M500 250 C600 245 720 255 865 190');
  $('.graph-lines [data-link="token"]').attr('d','M500 250 C585 350 710 425 575 460');
  const memoryTitles={project:'00-root-general-information',stack:'03-frontend-paketler',architecture:'03-frontend-react',style:'05-uygulama-workflow',previous:'04-active-context',output:'01-api-integration',task:'05-planlama-workflow',files:'03-frontend-servis-envanteri',solid:'03-frontend-ui-komponentleri',avoid:'03-frontend-auth-akisi',token:'03-frontend-hook-envanteri'};
  Object.entries(memoryTitles).forEach(([node,title])=>$('.graph-node[data-node="'+node+'"] strong').first().text(title));
  $('.graph-stage').prepend('<button class="graph-arrow graph-prev" aria-label="Önceki slide">‹</button><button class="graph-arrow graph-next" aria-label="Sonraki slide">›</button>');
  $('.graph-prev,.graph-next,.slide-arrow').on('click',function(){const direction=$(this).hasClass('graph-prev')||$(this).hasClass('prev')?'prev':'next';$('.slide-dots i').removeClass('active').eq(direction==='next'?1:0).addClass('active');$('.slide-labels span').removeClass('active').eq(direction==='next'?1:0).addClass('active')});
  const routingSlide=`<div class="routing-slide" aria-hidden="true"><div class="routing-intro"><div><span>MODEL ROUTING</span><h2>Doğru <em>Görev</em> için Doğru Model</h2><p>Her görev aynı değildir. Agent; kapsam, reasoning ihtiyacı, süre ve risk sinyallerini analiz ederek en uygun modeli seçer.</p></div><aside>“Tek model her iş için en iyi seçenek değildir. Görev karakteri, model seçimini belirler.”<small>— SoruAsistanım</small></aside></div><div class="routing-board"><article class="signal-card"><h3>〽 Task Signals</h3><p>Görev analiz edilir ve temel sinyaller çıkarılır.</p><div><b>Scope</b><span>Küçük　—　Geniş</span></div><div><b>Reasoning</b><span>Düşük　—　Yüksek</span></div><div><b>Duration</b><span>Kısa　—　Uzun</span></div><div><b>Risk</b><span>Rutin　—　Kritik</span></div><div><b>Output</b><span>Plan / Kod / Görsel</span></div></article><div class="routing-flow"><div class="flow-step">▤ <span><b>Görev Geldi</b><small>Kullanıcı isteği veya otomatik görev</small></span></div><i>↓</i><div class="routing-engine">♧<b>Model Routing Engine</b><small>Görev analizi → kural eşleştirme<br>→ en uygun model seçimi</small></div><i>↓</i><div class="flow-step">⚙ <span><b>Agent Execution</b><small>Seçilen model ile görev yürütülür</small></span></div><i>↓</i><div class="flow-step">✓ <span><b>Kod Kontrolü / Build / Çıktı</b><small>Sonuçlar doğrulanır ve uygulanır</small></span></div></div><article class="rules-card"><h3>◇ Model Routing Rules</h3><p>Görev karakterine göre en uygun model seçilir.</p><div><b>Plan / Mimari Karar</b><small>DeepSeek V4 Pro · GPT-5.6 Sol</small></div><div><b>Küçük Düzeltme / Hızlı İş</b><small>DeepSeek V4 Flash</small></div><div><b>Görsel Karar / Yüksek Reasoning</b><small>GPT-5.6 Sol</small></div><div><b>Uzun ve Kritik Uygulama</b><small>GPT-5.6 Tera · Kimi K3 · DeepSeek V4 Pro</small></div></article></div><div class="routing-outcome"><b>◎ Doğru görev, doğru model, daha iyi sonuçlar.</b><span>Daha yüksek doğruluk</span><span>Daha hızlı geliştirme</span><span>Daha verimli token kullanımı</span><span>Daha az hata riski</span></div></div>`;
  $('.agents-content .slide-nav').before(routingSlide);
  $('.routing-slide').prepend('<button class="routing-arrow routing-prev" aria-label="Önceki slide">‹</button><button class="routing-arrow routing-next" aria-label="Sonraki slide">›</button>');
  const pipelineSlide=`<div class="pipeline-slide" aria-hidden="true"><div class="pipeline-intro"><span>AI QUESTION GENERATION PIPELINE</span><h2>Kurallı üretim, <em>güvenilir çıktı.</em></h2><p>AI'dan serbest metin almak yerine; müfredat, pedagojik kurallar, tekrar kontrolü ve şema doğrulamasıyla çalışan kontrollü bir soru üretim akışı kuruldu.</p></div><div class="pipeline-board"><article class="pipeline-input"><h3>▤ Müfredat Seçimi</h3><p>Üretim bağlamı, seçilen eğitim parametrelerinden oluşur.</p><div><b>Sınıf</b><span>3. / 4. Sınıf</span></div><div><b>Ders</b><span>Matematik</span></div><div><b>Ünite</b><span>Doğal Sayılar</span></div><div><b>Konu</b><span>Problem Çözme</span></div><div class="prompt-rules"><b>Prompt Rules</b><small>MEB müfredatı · yaşa uygun dil · dengeli zorluk · farklı soru türleri · tekrar önleme</small></div></article><div class="pipeline-core"><div class="pipe-step input">1　Context + Prompt</div><i>↓</i><div class="pipe-engine"><span>♧</span><b>AI Generation</b><small>Gemini ana sağlayıcı<br>OpenAI manuel üretim provider'ı</small></div><i>↓</i><div class="pipe-step json">2　Structured JSON Output</div><i>↓</i><div class="pipe-step validate">3　Parser + Validation + Retry</div></div><article class="pipeline-output"><h3>✓ Doğrulama ve İçeri Aktarma</h3><p>Üretim kalıcı değildir; onaydan önce kontrol edilir.</p><div class="json-schema"><b>{ Questions: [...] }</b><span>QuestionText · QuestionType · Difficulty</span><span>Options · CorrectAnswer · Explanation</span></div><ul><li>Geçersiz JSON toleranslı ayrıştırılır</li><li>Eksik / bozuk sorular elenir</li><li>Geçici hata ve 429 için retry uygulanır</li><li>Fallback model seçeneği devreye girer</li></ul><div class="approval">◎ Önizleme → Kullanıcı Onayı → Question Pool / PDF</div></article></div><div class="pipeline-footer"><b>“Prompt → Structured Output → Validation → Approved Content”</b><span>TickerQ ile 5 dakikalık otomatik üretim döngüsü</span></div><button class="pipeline-arrow pipeline-prev" aria-label="Önceki slide">‹</button><button class="pipeline-arrow pipeline-next" aria-label="Sonraki slide">›</button></div>`;
  $('.agents-content .slide-nav').before(pipelineSlide);
  $('.slide-labels span').eq(2).text('03 AI Pipeline');$('.slide-labels span').slice(3).remove();$('.slide-dots i').slice(3).remove();
  let agentSlideIndex=0,slideScrollLockedUntil=0;
  function showAgentSlide(index){agentSlideIndex=index;const second=index===1, third=index===2;$('.agents-heading,.graph-stage').toggle(!second&&!third);$('.routing-slide').toggleClass('open',second).attr('aria-hidden',!second);$('.pipeline-slide').toggleClass('open',third).attr('aria-hidden',!third);$('.slide-dots i,.slide-labels span').removeClass('active').eq(index).addClass('active')}
  $('.slide-labels span').each(function(i){$(this).on('click',function(){showAgentSlide(i)})});
  $('.graph-next,.slide-arrow.next').off('click').on('click',()=>showAgentSlide(1));$('.graph-prev,.slide-arrow.prev').off('click').on('click',()=>showAgentSlide(0));
  $('.routing-prev').on('click',()=>showAgentSlide(0));$('.routing-next').on('click',()=>showAgentSlide(2));
  $('.pipeline-prev').on('click',()=>showAgentSlide(1));$('.pipeline-next').on('click',()=>showAgentSlide(2));
  window.addEventListener('wheel',function(event){if(window.innerWidth<=760||Math.abs(event.deltaY)<12)return;const section=document.getElementById('agents'),rect=section.getBoundingClientRect(),focused=rect.top<=80&&rect.bottom>=window.innerHeight-80;if(!focused)return;if(Date.now()<slideScrollLockedUntil){event.preventDefault();return}const down=event.deltaY>0;if((down&&agentSlideIndex<2)||(!down&&agentSlideIndex>0)){event.preventDefault();slideScrollLockedUntil=Date.now()+650;showAgentSlide(agentSlideIndex+(down?1:-1))}}, {passive:false});
  const promptExampleSlide=`<div class="examples-slide prompt-example-slide" aria-hidden="true"><div class="example-prompt-heading"><span>REAL EXAMPLES / IMPLEMENTATION</span><h2>Standarta uygun <em>örnek promptum</em></h2><p>Net amaç, kapsam sınırı, ilgili dosyalar, doğrulama adımı ve beklenen çıktı tek bir yönergede birleştiğinde agent değişikliği doğrudan ve güvenli biçimde uygular.</p></div><div class="example-prompt-board"><div class="example-image"><img src="assets/images/2.png" alt="Standarta uygun örnek prompt ekranı" /></div><aside class="example-result"><h3>✓ Beklenen Sonuç</h3><div><b>Tek kalemde uygulama</b><small>İstenen değişiklikler net bir görev zinciriyle tamamlanır.</small></div><div><b>Daraltılmış çalışma alanı</b><small>Agent yalnız ilgili dosya ve çağrı zincirinde çalışır.</small></div><div><b>Minimum hallucination riski</b><small>Bağlam, sınırlar ve kabul kriterleri açıkça tanımlıdır.</small></div><div><b>Hızlı ve verimli çıktı</b><small>Gereksiz repository taraması azalır; hedef, %80'e varan token tasarrufudur.</small></div></aside></div><div class="example-summary"><b>AMAÇ <i>→</i> KAPSAM <i>→</i> REFERANS <i>→</i> DOĞRULAMA <i>→</i> KRİTİK ÇIKTI</b><span>Doğru prompt, agent için bir görev tanımı değil; uygulanabilir bir çalışma sözleşmesidir.</span></div><button class="examples-arrow examples-prev" aria-label="Önceki slide">‹</button><button class="examples-arrow examples-next" aria-label="Sonraki slide">›</button></div>`;
  $('.examples-nav').before(promptExampleSlide);$('.examples-nav').append('<i></i><span>02 Örnek Prompt</span>');
  $('.examples-content > .examples-slide').first().append('<button class="examples-arrow examples-first-prev" aria-label="Önceki slide" aria-disabled="true">‹</button><button class="examples-arrow examples-first-next" aria-label="Sonraki slide">›</button>');
  const benchmarkSlide=`<div class="examples-slide benchmark-slide" aria-hidden="true"><div class="benchmark-heading"><span>REAL EXAMPLES / MEMORY BENCHMARK</span><h2>Graphify CodeBase vs <em>Custom</em><br><small>(SoruAsistanı) Memory</small></h2><p>Graphify CodeBase'in <b class="highlight-violet">%98.5'e yakın token tasarrufu</b> sağladığı iddiasını, SoruAsistanı için kurduğum memory yapısında <b class="highlight-cyan">Sub Agentlar</b> ile bir <b class="highlight-blue">Benchmark</b> çalışmasına dönüştürdüm.</p></div><div class="benchmark-board"><div class="benchmark-image"><img class="zoomable-image" src="assets/images/1.png" alt="Graphify ve SoruAsistanı Memory benchmark karşılaştırması" /></div><aside class="benchmark-result"><span>BENCHMARK SONUCU</span><h3>SoruAsistanı Memory,<br>Graphify'dan</h3><div class="benchmark-stat"><b>2.5×</b><small>Daha Hızlı</small></div><div class="benchmark-stat"><b>5×</b><small>Daha Ucuz</small></div><p>Göreve özel memory, ilgili referansları daraltarak sub agent'ların daha kısa ve odaklı context ile çalışmasını sağladı.</p></aside></div><div class="benchmark-flow"><b>GRAPHIFY CODEBASE</b><i>vs</i><b class="winner">CUSTOM SORUASİSTANI MEMORY</b><span>Göreve özel context · Sub Agent routing · Daha az gereksiz tarama</span></div><button class="examples-arrow examples-prev benchmark-prev" aria-label="Önceki slide">‹</button><button class="examples-arrow examples-next benchmark-next" aria-label="Sonraki slide">›</button></div>`;
  $('.examples-nav').before(benchmarkSlide);$('.examples-nav').append('<i></i><span>03 Memory Benchmark</span>');
  let examplesSlideIndex=0,examplesScrollLockedUntil=0;
  function showExamplesSlide(index){examplesSlideIndex=index;$('.examples-content > .examples-slide').toggleClass('open',false).attr('aria-hidden','true').eq(index).addClass('open').attr('aria-hidden','false');$('.examples-nav i').removeClass('active').eq(index).addClass('active');$('.examples-nav span').removeClass('active').eq(index).addClass('active')}
  $('.examples-nav span').each(function(i){$(this).on('click',()=>showExamplesSlide(i))});$('.examples-first-next').on('click',()=>showExamplesSlide(1));$('.examples-prev').on('click',()=>showExamplesSlide(0));$('.prompt-example-slide .examples-next').off('click').on('click',()=>showExamplesSlide(2));$('.benchmark-prev').on('click',()=>showExamplesSlide(1));$('.benchmark-next').on('click',()=>showExamplesSlide(2));
  $('.prompt-visual img,.example-image img').addClass('zoomable-image').attr('tabindex','0').attr('role','button').attr('aria-label','Görseli büyüt');
  $('body').append('<div class="image-lightbox" aria-hidden="true"><button class="image-lightbox-close" aria-label="Görseli kapat">×</button><img alt="Büyütülmüş görsel" /></div>');
  function closeImageZoom(){$('.image-lightbox').removeClass('open').attr('aria-hidden','true')}
  $(document).on('click keydown','.zoomable-image',function(event){if(event.type==='keydown'&&event.key!=='Enter'&&event.key!==' ')return;event.preventDefault();$('.image-lightbox img').attr('src',$(this).attr('src'));$('.image-lightbox').addClass('open').attr('aria-hidden','false')});
  $('.image-lightbox,.image-lightbox-close').on('click',function(event){if(event.target===this||$(event.target).hasClass('image-lightbox-close'))closeImageZoom()});$(document).on('keydown',function(event){if(event.key==='Escape')closeImageZoom()});
  window.addEventListener('wheel',function(event){if(window.innerWidth<=760||Math.abs(event.deltaY)<12)return;const section=document.getElementById('examples'),rect=section.getBoundingClientRect(),focused=rect.top<=80&&rect.bottom>=window.innerHeight-80;if(!focused)return;if(Date.now()<examplesScrollLockedUntil){event.preventDefault();return}const down=event.deltaY>0;if((down&&examplesSlideIndex<2)||(!down&&examplesSlideIndex>0)){event.preventDefault();examplesScrollLockedUntil=Date.now()+650;showExamplesSlide(examplesSlideIndex+(down?1:-1))}}, {passive:false});
  $('.graph-node:not(.center-node)').on('click',function(){const d=mdNodes[$(this).data('node')];$('.popup-title').text(d[0]);$('.popup-copy').text(d[1]);$('.popup-link').attr('href',d[2]);$('.node-popup').addClass('open').attr('aria-hidden','false');$('.graph-node').removeClass('selected').filter(this).addClass('selected')});$('.popup-close').on('click',function(){$('.node-popup').removeClass('open').attr('aria-hidden','true');$('.graph-node').removeClass('selected')});$('.graph-node:not(.center-node)').on('mouseenter',function(){$('.graph-stage').addClass('node-focus');$('.graph-lines path').addClass('dim');$('.graph-lines path[data-link="'+$(this).data('node')+'"]').removeClass('dim').addClass('highlight')}).on('mouseleave',function(){$('.graph-stage').removeClass('node-focus');$('.graph-lines path').removeClass('dim highlight')});
});
